const express = require('express');
const router = express.Router();

const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const roleRoutes = require('./role.routes');
const productRoutes = require('./product.routes');
const distributorRoutes = require('./distributor.routes');
const inventoryRoutes = require('./inventory.routes');
const pharmacyRoutes = require('./pharmacy.routes');
const doctorRoutes = require('./doctor.routes');
const doctorActivityRoutes = require('./doctorActivity.routes');
const orderRoutes = require('./order.routes');
const paymentRoutes = require('./payment.routes');
const collectionRoutes = require('./collection.routes');
const settlementRoutes = require('./settlement.routes');
const ledgerRoutes = require('./ledger.routes');
const targetRoutes = require('./target.routes');
const weeklyPlanRoutes = require('./weeklyPlan.routes');
const planItemRoutes = require('./planItem.routes');
const visitRoutes = require('./visit.routes');
const expenseRoutes = require('./expense.routes');
const payrollRoutes = require('./payroll.routes');
const attendanceRoutes = require('./attendance.routes');
const salaryStructureRoutes = require('./salaryStructure.routes');
const reportRoutes = require('./report.routes');
const dashboardRoutes = require('./dashboard.routes');
const supplierRoutes = require('./supplier.routes');
const procurementRoutes = require('./procurement.routes');
const auditLogRoutes = require('./auditLog.routes');
const superAdminRoutes = require('./superAdmin.routes');
const platformRoutes = require('./platform.routes');

router.use('/auth', authRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/platform', platformRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/products', productRoutes);
router.use('/distributors', distributorRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/pharmacies', pharmacyRoutes);
router.use('/doctors', doctorRoutes);
router.use('/doctor-activities', doctorActivityRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/collections', collectionRoutes);
router.use('/settlements', settlementRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/targets', targetRoutes);
router.use('/weekly-plans', weeklyPlanRoutes);
router.use('/plan-items', planItemRoutes);
router.use('/visits', visitRoutes);
router.use('/expenses', expenseRoutes);
router.use('/payroll', payrollRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/salary-structures', salaryStructureRoutes);
router.use('/reports', reportRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/procurement', procurementRoutes);
router.use('/audit-logs', auditLogRoutes);

module.exports = router;
