const express = require('express');
const router = express.Router();

const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const roleRoutes = require('./role.routes');
const productRoutes = require('./product.routes');
const brandRoutes = require('./brand.routes');
const productTaxonomyRoutes = require('./productTaxonomy.routes');
const presentationRoutes = require('./presentation.routes');
const catalogCampaignRoutes = require('./catalogCampaign.routes');
const productKitRoutes = require('./productKit.routes');
const distributorRoutes = require('./distributor.routes');
const inventoryRoutes = require('./inventory.routes');
const pharmacyRoutes = require('./pharmacy.routes');
const doctorRoutes = require('./doctor.routes');
const doctorImportRoutes = require('./doctorImport.routes');
const doctorActivityRoutes = require('./doctorActivity.routes');
const orderRoutes = require('./order.routes');
const paymentRoutes = require('./payment.routes');
const collectionRoutes = require('./collection.routes');
const settlementRoutes = require('./settlement.routes');
const ledgerRoutes = require('./ledger.routes');
const targetRoutes = require('./target.routes');
const weeklyPlanRoutes = require('./weeklyPlan.routes');
const callPointRoutes = require('./callPoint.routes');
const planItemRoutes = require('./planItem.routes');
const visitRoutes = require('./visit.routes');
const expenseRoutes = require('./expense.routes');
const payrollRoutes = require('./payroll.routes');
const attendanceRoutes = require('./attendance.routes');
const salaryStructureRoutes = require('./salaryStructure.routes');
const reportRoutes = require('./report.routes');
const dashboardRoutes = require('./dashboard.routes');
const supplierRoutes = require('./supplier.routes');
const procurementRoutes = require('./procurement.routes');
const auditLogRoutes = require('./auditLog.routes');
const superAdminRoutes = require('./superAdmin.routes');
const platformRoutes = require('./platform.routes');
const territoryRoutes = require('./territory.routes');
const territoryImportRoutes = require('./territoryImport.routes');
const onboardingRoutes = require('./onboarding.routes');
const accountingReportRoutes = require('./accountingReport.routes');
const accountRoutes = require('./account.routes');
const voucherRoutes = require('./voucher.routes');
const mobileAuthRoutes = require('./mobileAuth.routes');
const deviceControlRoutes = require('./deviceControl.routes');
const syncRoutes = require('./sync.routes');
const mediaRoutes = require('./media.routes');
const notificationRoutes = require('./notification.routes');
const doctorLocationSuggestionRoutes = require('./doctorLocationSuggestion.routes');
const announcementRoutes = require('./announcement.routes');
const calendarRoutes = require('./calendar.routes');
const geoRoutes = require('../../geo/routes/geo.routes');
const realtimeRoutes = require('./realtime.routes');
const internalMetricsRoutes = require('./internalMetrics.routes');

router.use('/auth/mobile', mobileAuthRoutes);
router.use('/device-control', deviceControlRoutes);
router.use('/sync', syncRoutes);
router.use('/media', mediaRoutes);
router.use('/notifications', notificationRoutes);
router.use('/announcements', announcementRoutes);
router.use('/auth', authRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/platform', platformRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/products', productRoutes);
router.use('/brands', brandRoutes);
router.use('/product-taxonomy', productTaxonomyRoutes);
router.use('/presentations', presentationRoutes);
router.use('/catalog-campaigns', catalogCampaignRoutes);
router.use('/product-kits', productKitRoutes);
router.use('/distributors', distributorRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/pharmacies', pharmacyRoutes);
// Mount /doctors/import BEFORE /doctors so the existing `/:id` route in doctorRoutes
// doesn't try to resolve "import" as an ObjectId.
router.use('/doctors/import', doctorImportRoutes);
router.use('/doctors', doctorRoutes);
router.use('/doctor-location-suggestions', doctorLocationSuggestionRoutes);
router.use('/doctor-activities', doctorActivityRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/collections', collectionRoutes);
router.use('/settlements', settlementRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/accounts', accountRoutes);
router.use('/vouchers', voucherRoutes);
router.use('/accounting-reports', accountingReportRoutes);
router.use('/targets', targetRoutes);
router.use('/calendar', calendarRoutes);
router.use('/weekly-plans', weeklyPlanRoutes);
router.use('/call-points', callPointRoutes);
router.use('/plan-items', planItemRoutes);
router.use('/visits', visitRoutes);
router.use('/expenses', expenseRoutes);
router.use('/payroll', payrollRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/salary-structures', salaryStructureRoutes);
router.use('/reports', reportRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/procurement', procurementRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/territories/import', territoryImportRoutes);
router.use('/territories', territoryRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/geo', geoRoutes);
router.use('/realtime', realtimeRoutes);
router.use('/internal/metrics', internalMetricsRoutes);

module.exports = router;
