const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MEDICAL_REP: 'MEDICAL_REP'
};

/** Tenant model: company users vs platform (multi-company) users. */
const USER_TYPES = {
  COMPANY: 'COMPANY',
  PLATFORM: 'PLATFORM'
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  PARTIALLY_DELIVERED: 'PARTIALLY_DELIVERED',
  DELIVERED: 'DELIVERED',
  PARTIALLY_RETURNED: 'PARTIALLY_RETURNED',
  RETURNED: 'RETURNED',
  CANCELLED: 'CANCELLED'
};

const LEDGER_TYPE = {
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT'
};

const LEDGER_ENTITY_TYPE = {
  PHARMACY: 'PHARMACY',
  /** Net clearing: positive balance (DR-CR) = distributor owes company; negative = company owes distributor. entityId = distributorId */
  DISTRIBUTOR_CLEARING: 'DISTRIBUTOR_CLEARING'
};

const COLLECTOR_TYPE = {
  COMPANY: 'COMPANY',
  DISTRIBUTOR: 'DISTRIBUTOR'
};

const SETTLEMENT_DIRECTION = {
  DISTRIBUTOR_TO_COMPANY: 'DISTRIBUTOR_TO_COMPANY',
  COMPANY_TO_DISTRIBUTOR: 'COMPANY_TO_DISTRIBUTOR'
};

const LEDGER_REFERENCE_TYPE = {
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  RETURN: 'RETURN',
  DELIVERY: 'DELIVERY',
  COLLECTION: 'COLLECTION',
  SETTLEMENT: 'SETTLEMENT',
  RETURN_CLEARING_ADJ: 'RETURN_CLEARING_ADJ'
};

/** meta.portion on COLLECTION lines in DISTRIBUTOR_CLEARING */
const LEDGER_COLLECTION_PORTION = {
  /** Distributor collected cash: company’s share to remit to company */
  REMITTANCE_DUE_TO_COMPANY: 'REMITTANCE_DUE_TO_COMPANY',
  /** Distributor collected cash: distributor’s commission on TP (portion of this collection) */
  DISTRIBUTOR_COMMISSION_ON_COLLECTION: 'DISTRIBUTOR_COMMISSION_ON_COLLECTION',
  /** Company collected cash: commission owed by company to distributor on this slice */
  COMMISSION_PAYABLE_TO_DISTRIBUTOR: 'COMMISSION_PAYABLE_TO_DISTRIBUTOR'
};

const TRANSACTION_TYPE = {
  SALE: 'SALE',
  RETURN: 'RETURN',
  EXPENSE: 'EXPENSE'
};

const PAYMENT_METHOD = {
  CASH: 'CASH',
  CHEQUE: 'CHEQUE',
  BANK_TRANSFER: 'BANK_TRANSFER',
  UPI: 'UPI'
};

const EXPENSE_CATEGORY = {
  DOCTOR_INVESTMENT: 'DOCTOR_INVESTMENT',
  SALARY: 'SALARY',
  RENT: 'RENT',
  LOGISTICS: 'LOGISTICS',
  OFFICE: 'OFFICE',
  OTHER: 'OTHER'
};

const PAYROLL_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID'
};

const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  HALF_DAY: 'HALF_DAY',
  LEAVE: 'LEAVE'
};

const ATTENDANCE_MARKED_BY = {
  SELF: 'SELF',
  ADMIN: 'ADMIN'
};

const WEEKLY_PLAN_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  /** @deprecated legacy workflow — retained for existing rows */
  SUBMITTED: 'SUBMITTED',
  /** @deprecated legacy workflow */
  REVIEWED: 'REVIEWED'
};

const PLAN_ITEM_TYPE = {
  DOCTOR_VISIT: 'DOCTOR_VISIT',
  OTHER_TASK: 'OTHER_TASK'
};

const PLAN_ITEM_STATUS = {
  PENDING: 'PENDING',
  VISITED: 'VISITED',
  MISSED: 'MISSED'
};

/** Doctor investment / commitment tracking (TP-based achieved sales) */
const DOCTOR_ACTIVITY_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

/** Procurement PO lifecycle — no stock / no supplier liability until GRN (Phase 2+). */
const PURCHASE_ORDER_STATUS = {
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
};

/** GRN posting state; inventory + supplier PURCHASE ledger only after POSTED (Phase 2+). */
const GOODS_RECEIPT_NOTE_STATUS = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED'
};

const SUPPLIER_INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED'
};

/**
 * Supplier (factory) liability ledger — not PnL.
 * PURCHASE increases payable; PAYMENT reduces it; ADJUSTMENT handles invoice↔GRN mismatch (Phase 3+).
 */
const SUPPLIER_LEDGER_TYPE = {
  PURCHASE: 'PURCHASE',
  PAYMENT: 'PAYMENT',
  ADJUSTMENT: 'ADJUSTMENT'
};

/** When type === ADJUSTMENT: whether payable goes up (like purchase) or down (like payment). */
const SUPPLIER_LEDGER_ADJUSTMENT_EFFECT = {
  INCREASE_PAYABLE: 'INCREASE_PAYABLE',
  DECREASE_PAYABLE: 'DECREASE_PAYABLE'
};

const SUPPLIER_LEDGER_REFERENCE_TYPE = {
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  MANUAL: 'MANUAL',
  /** Procurement: liability from posted GRN — referenceId = GoodsReceiptNote */
  GOODS_RECEIPT_NOTE: 'GOODS_RECEIPT_NOTE',
  /** Optional link to supplier invoice document */
  SUPPLIER_INVOICE: 'SUPPLIER_INVOICE',
  /** Invoice vs GRN / other procurement adjustments */
  PROCUREMENT_ADJUSTMENT: 'PROCUREMENT_ADJUSTMENT'
};

/** Recorded on SupplierLedger rows where type === PAYMENT (audit / voucher) */
const SUPPLIER_PAYMENT_METHOD = {
  CASH: 'CASH',
  BANK: 'BANK',
  CHEQUE: 'CHEQUE',
  OTHER: 'OTHER'
};

const SUPPLIER_PAYMENT_VERIFICATION = {
  VERIFIED: 'VERIFIED',
  UNVERIFIED: 'UNVERIFIED'
};

module.exports = {
  ROLES,
  USER_TYPES,
  ORDER_STATUS,
  LEDGER_TYPE,
  LEDGER_ENTITY_TYPE,
  COLLECTOR_TYPE,
  SETTLEMENT_DIRECTION,
  LEDGER_REFERENCE_TYPE,
  LEDGER_COLLECTION_PORTION,
  TRANSACTION_TYPE,
  PAYMENT_METHOD,
  EXPENSE_CATEGORY,
  PAYROLL_STATUS,
  ATTENDANCE_STATUS,
  ATTENDANCE_MARKED_BY,
  WEEKLY_PLAN_STATUS,
  PLAN_ITEM_TYPE,
  PLAN_ITEM_STATUS,
  DOCTOR_ACTIVITY_STATUS,
  PURCHASE_ORDER_STATUS,
  GOODS_RECEIPT_NOTE_STATUS,
  SUPPLIER_INVOICE_STATUS,
  SUPPLIER_LEDGER_TYPE,
  SUPPLIER_LEDGER_ADJUSTMENT_EFFECT,
  SUPPLIER_LEDGER_REFERENCE_TYPE,
  SUPPLIER_PAYMENT_METHOD,
  SUPPLIER_PAYMENT_VERIFICATION
};
