const ONBOARDING_STATUS = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  READY_FOR_GO_LIVE: 'READY_FOR_GO_LIVE',
  LIVE: 'LIVE',
  ARCHIVED: 'ARCHIVED',
  FAILED: 'FAILED'
};

const ONBOARDING_STEP = {
  COMPANY_SETUP: 'COMPANY_SETUP',
  MASTER_DATA: 'MASTER_DATA',
  OPENING_STOCK: 'OPENING_STOCK',
  OPENING_BALANCES: 'OPENING_BALANCES',
  OPTIONAL_HISTORY: 'OPTIONAL_HISTORY',
  VERIFICATION: 'VERIFICATION',
  GO_LIVE: 'GO_LIVE'
};

const IMPORT_MODE = {
  DRY_RUN: 'DRY_RUN',
  COMMIT: 'COMMIT'
};

const IMPORT_JOB_STATUS = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

const IMPORT_ROW_STATUS = {
  PENDING: 'PENDING',
  VALID: 'VALID',
  INVALID: 'INVALID',
  SKIPPED: 'SKIPPED',
  COMMITTED: 'COMMITTED',
  FAILED: 'FAILED'
};

module.exports = {
  ONBOARDING_STATUS,
  ONBOARDING_STEP,
  IMPORT_MODE,
  IMPORT_JOB_STATUS,
  IMPORT_ROW_STATUS
};
