module.exports = {
  Company: require('./Company'),
  User: require('./User'),
  Product: require('./Product'),
  Distributor: require('./Distributor'),
  DistributorInventory: require('./DistributorInventory'),
  StockTransfer: require('./StockTransfer'),
  Pharmacy: require('./Pharmacy'),
  Doctor: require('./Doctor'),
  DoctorActivity: require('./DoctorActivity'),
  Order: require('./Order'),
  DeliveryRecord: require('./DeliveryRecord'),
  ReturnRecord: require('./ReturnRecord'),
  Ledger: require('./Ledger'),
  Payment: require('./Payment'),
  Transaction: require('./Transaction'),
  MedRepTarget: require('./MedRepTarget'),
  WeeklyPlan: require('./WeeklyPlan'),
  PlanItem: require('./PlanItem'),
  VisitLog: require('./VisitLog'),
  Expense: require('./Expense'),
  Payroll: require('./Payroll'),
  SalaryStructure: require('./SalaryStructure'),
  Attendance: require('./Attendance'),
  AuditLog: require('./AuditLog'),
  Supplier: require('./Supplier'),
  SupplierLedger: require('./SupplierLedger')
};
